### A CI workflow template that runs linting and python testing
### TODO: Modify as needed or as desired.

name: Test tap-hubspot-sdk

on: [push]

jobs:
  linting:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Only lint using the primary version used for dev
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.1.8
    - name: Install dependencies
      run: |
        poetry install
    - name: Run lint command from tox.ini
      run: |
        poetry run tox -e lint

  pytest:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.1.11
    - name: Install dependencies
      run: |
        poetry install
    - name: Test with pytest
      id: test_pytest
      continue-on-error: true
      env:
         access_token: ${{ secrets.access_token }}
         api_version_1: ${{ secrets.api_version_1 }}
         api_version_2: ${{ secrets.api_version_2 }}
         api_version_3: ${{ secrets.api_version_3 }}
         api_version_4: ${{ secrets.api_version_4 }}
         auth_type: ${{ secrets.auth_type }}
      run: |
        poetry run pytest --capture=no
